// <auto-generated />
using System;
using MRQ.CryptoBot.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MRQ.CryptoBot.Repository.Migrations
{
    [DbContext(typeof(SQLiteContext))]
    [Migration("20220205195807_umum")]
    partial class umum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("MRQ.CryptoBot.Domains.Entities.Configurations.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChainType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContractABI")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractRouterForSwap")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultGas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultGasPrice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SlippageTolerance")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeBetweenPriceUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeBetweenWalletBalanceUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeForPingConnectionWithInternet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimeForPingConnectionWithWeb3")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenDefaultContract")
                        .HasColumnType("TEXT");

                    b.Property<string>("Web3Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("MRQ.CryptoBot.Domains.Entities.Configurations.Router", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoutersForSwapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SwapOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoutersForSwapId");

                    b.ToTable("Router");
                });

            modelBuilder.Entity("MRQ.CryptoBot.Domains.Entities.Configurations.RoutersForSwap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("RoutersForSwap");
                });

            modelBuilder.Entity("MRQ.CryptoBot.Domains.Entities.Moralis.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("MoralisApiKey");
                });

            modelBuilder.Entity("MRQ.CryptoBot.Domains.Entities.Moralis.Balance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExchangeAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UsdPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Balances");
                });

            modelBuilder.Entity("MRQ.CryptoBot.Domains.Entities.Moralis.NativePrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BalanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Decimals")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BalanceId");

                    b.ToTable("NativePrices");
                });

            modelBuilder.Entity("MRQ.CryptoBot.Domains.Entities.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<string>("BalanceWei")
                        .HasColumnType("TEXT");

                    b.Property<string>("Decimals")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("MRQ.CryptoBot.Domains.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adress")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrivateKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("MRQ.CryptoBot.Domains.Entities.Configurations.Router", b =>
                {
                    b.HasOne("MRQ.CryptoBot.Domains.Entities.Configurations.RoutersForSwap", null)
                        .WithMany("Router")
                        .HasForeignKey("RoutersForSwapId");
                });

            modelBuilder.Entity("MRQ.CryptoBot.Domains.Entities.Configurations.RoutersForSwap", b =>
                {
                    b.HasOne("MRQ.CryptoBot.Domains.Entities.Configurations.Configuration", null)
                        .WithMany("RoutersForSwaps")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MRQ.CryptoBot.Domains.Entities.Moralis.ApiKey", b =>
                {
                    b.HasOne("MRQ.CryptoBot.Domains.Entities.Configurations.Configuration", null)
                        .WithMany("MoralisApiKeys")
                        .HasForeignKey("ConfigurationId");
                });

            modelBuilder.Entity("MRQ.CryptoBot.Domains.Entities.Moralis.NativePrice", b =>
                {
                    b.HasOne("MRQ.CryptoBot.Domains.Entities.Moralis.Balance", "Balance")
                        .WithMany()
                        .HasForeignKey("BalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Balance");
                });

            modelBuilder.Entity("MRQ.CryptoBot.Domains.Entities.Configurations.Configuration", b =>
                {
                    b.Navigation("MoralisApiKeys");

                    b.Navigation("RoutersForSwaps");
                });

            modelBuilder.Entity("MRQ.CryptoBot.Domains.Entities.Configurations.RoutersForSwap", b =>
                {
                    b.Navigation("Router");
                });
#pragma warning restore 612, 618
        }
    }
}
